### ISSUE TITLE
update-in-place triggered for every apply when tactics are defined on azurerm_sentinel_alert_rule_scheduled resource

### ISSUE THREAD

**Issue by jstaffin-presidio** [terraform-providers/terraform-provider-azurerm#11191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azurerm v2.53.0

### Affected Resource(s)

* `azurerm_sentinel_alert_rule_scheduled`

### Terraform Configuration Files

```hcl
locals {
  customer = {
    name      = var.customer-name
    workspace = var.customer-workspace
  }
  exclusions = yamldecode(file("${path.module}/exclusions.yaml"))
}

# Specify any resources

# Creates a rule entry for each file in the rules folder
module "core_rules" {
  source = "git::https://gitlab.prod.presidiosecure.com/azure-sentinel/modules/core-rules.git?ref=v0.1.2"
  customer-name = local.customer.name
  customer-workspace = local.customer.workspace
  exclusions = local.exclusions
}

resource "azurerm_sentinel_alert_rule_scheduled" "customer-rules" {
  for_each = {
    for f in setsubtract(fileset("${path.module}/rules/", "*.yaml.tpl"), local.exclusions) : f => {
      rule            = yamldecode(templatefile("${path.module}/rules/${f}", local.customer))
      trimmed_filname = regex("^(.+?)\\.", f)[0]
    }
  }
  name                       = "${each.value.trimmed_filname}-${replace(var.customer-name, "/[^0-9A-Za-z]/", "")}"
  log_analytics_workspace_id = data.terraform_remote_state.vsoc-sentinel.outputs.sentinel-workspace-id
  display_name               = each.value.rule.DisplayName
  severity                   = each.value.rule.Severity
  query                      = each.value.rule.Query
  description                = coalesce(each.value.rule.Description, " ")
  enabled                    = each.value.rule.Enabled
  query_frequency            = "PT${each.value.rule.QueryFrequency.Hours}H"
  query_period               = "PT${each.value.rule.QueryPeriod.Hours}H"
  suppression_duration       = "PT${each.value.rule.SuppressionDuration.Hours}H"
  suppression_enabled        = each.value.rule.SuppressionEnabled
  tactics                    = each.value.rule.Tactics
  trigger_operator           = each.value.rule.TriggerOperator
  trigger_threshold          = each.value.rule.TriggerThreshold
  event_grouping {
    aggregation_method = each.value.rule.EventGrouping.AggregationMethod
  }
  incident_configuration {
    create_incident = each.value.rule.IncidentConfiguration.CreateIncident
    grouping {
      enabled                 = each.value.rule.IncidentConfiguration.Grouping.Enabled
      lookback_duration       = "PT${each.value.rule.IncidentConfiguration.Grouping.LookbackDuration.Minutes}M"
      reopen_closed_incidents = each.value.rule.IncidentConfiguration.Grouping.ReopenClosedIncidents
      entity_matching_method  = each.value.rule.IncidentConfiguration.Grouping.EntityMatchingMethod
      group_by                = each.value.rule.IncidentConfiguration.Grouping.GroupBy
    }
  }
}
```

### Input YAML Template file

```yaml
DisplayName: Atypical Travel - ${name}
Description: ''
Enabled: true
Query: 'workspace("${workspace}").SecurityAlert
  | where AlertType == "ImpossibleTravel"'
QueryFrequency:
  Hours: 5
QueryPeriod:
  Hours: 5
Severity: Medium
SuppressionDuration:
  Hours: 5
SuppressionEnabled: false
TriggerOperator: GreaterThan
TriggerThreshold: 0
Tactics:
  - InitialAccess
EventGrouping:
  AggregationMethod: "SingleAlert" # Options are SingleAlert or AlertPerResult
IncidentConfiguration:
  CreateIncident: true
  Grouping:
    Enabled: false
    LookbackDuration:
        Minutes: 5
    ReopenClosedIncidents: false
    EntityMatchingMethod: "None" # OEntityMatchingMethod ptions are All, Custom and None
    GroupBy: # GroupBy Only required when EntityMatchingMethod is set to custom above
      - Account
      - Host
      - Url
      - Ip
```

### Debug Output

https://gist.github.com/jstaffin-presidio/791da565c68237bb7e2d6fc77cb340d5

### Expected Behaviour

The values for Tactics have not changed in the terraform module or variables and are indeed set correctly in the deployed infrastructure.  There should be no triggered update-in-place.  

### Actual Behaviour

An update-in-place is triggered on every apply, attempting to change "IP" to "Ip" and "URL" to "Url"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I attempted to change the source variables in the YAML template to "IP" and "URL" and the module does not accept these as valid options, it requires the lowercase versions
