### ISSUE TITLE
DHGROUP & PFS Choices Issue

### ISSUE THREAD

**Issue by nemrood** [terraform-providers/terraform-provider-azurerm#12179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5
AzureRM v2.60

### Affected Resource(s)

azurerm_vpn_gateway_connection

### Terraform Configuration Files

module.tf
```hcl
resource "azurerm_vpn_gateway_connection" "vpnconn" {
  name               = var.vpnconnection_name
  vpn_gateway_id     = var.vpn_gateway_id
  remote_vpn_site_id = azurerm_vpn_site.vpnsite.id
  
  dynamic "vpn_link" {
    for_each = var.links
    content {

      name                           = vpn_link.value.connection["name"]
      bandwidth_mbps                 = vpn_link.value.connection["bandwidth_mbps"]
      vpn_site_link_id               = azurerm_vpn_site.vpnsite.link[vpn_link.key].id
      local_azure_ip_address_enabled = vpn_link.value.connection["local_azure_ip_address_enabled"]
      shared_key                     = var.psk
      policy_based_traffic_selector_enabled = vpn_link.value.connection["policy_based_traffic_selector_enabled"]
      dynamic "ipsec_policy" {
        for_each       = var.payload ? [1] : []
        content { 
             
          dh_group                     = vpn_link.value.ipsec_policy["dh_group"]
          ike_encryption_algorithm     = vpn_link.value.ipsec_policy["ike_encryption_algorithm"]
          ike_integrity_algorithm      = vpn_link.value.ipsec_policy["ike_integrity_algorithm"]
          encryption_algorithm         = vpn_link.value.ipsec_policy["encryption_algorithm"]
          integrity_algorithm          = vpn_link.value.ipsec_policy["integrity_algorithm"]
          pfs_group                    = vpn_link.value.ipsec_policy["pfs_group"]
          sa_data_size_kb              = vpn_link.value.ipsec_policy["sa_data_size_kb"]
          sa_lifetime_sec              = vpn_link.value.ipsec_policy["sa_lifetime_sec"]
        }
      }
    }
  }
}
```

values.yaml
```
      - name: "Link"
        speed_in_mbps: "200"
        provider_name: "ER_via_AT&T"
        pip_fqdn: "xx.xx.xx.xx"
        connection:
          name: "ER-Link-Connection"
          local_azure_ip_address_enabled: "true" #for vpn over er
          bandwidth_mbps: "200"
          policy_based_traffic_selector_enabled: "true"
        ipsec_policy:
          dh_group: "DHGroup2"
          ike_encryption_algorithm: "AES256"
          ike_integrity_algorithm: "SHA256"
          encryption_algorithm: "AES256"
          integrity_algorithm: "SHA256"
          pfs_group: "PFS2"
          sa_data_size_kb: "1024"
          sa_lifetime_sec: "27000"
```

### Debug Output

Error: creating Vpn Gateway Connection Resource "vWAN-TS-Connections" (Resource Group "MASKED" / VPN Gateway "MASKED"): network.VpnConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidDhGroupSpecifiedForResource" Message="Invalid DhGroup specified for Resource /subscriptions/MASKED/resourceGroups/MASKED/providers/Microsoft.Network/vpnGateways/MASKED/vpnConnections/MASKED/vpnLinkConnections/ER-Link-Connection. The allowed DhGroup values are DHGroup14,DHGroup24,ECP256,ECP384." Details=[]

### Panic Output

no panic

### Expected Behaviour

in the ipsec_policy block, we should be able to set the DHGroup attribute to DHGroup1 or DHGroup2 and the PFS attribute to PFS1 or PFS2.

### Actual Behaviour

-->Terraform/Azure rejects the choice and says the only allowed values are :  DHGroup14,DHGroup24,ECP256,ECP384
-->SAME Problem for PFS.

**NOTE**: on terraform documentation we can see that DHGROUP1, DHGROUP2, PFS1 and PFS2 are valid options, we can also set them via scripts or az  cli, but when using terraform it just gives the error shown above.

### Steps to Reproduce

Standard Process (init, validate, plan, apply).

### Important Factoids

Public Azure

### References

None

* #0000
