### ISSUE TITLE
Cant Authenticate with AKS_WORKLOAD_IDENTITY in Devops Pipeline

### ISSUE THREAD

**Issue by MarkTallentire** [terraform-providers/terraform-provider-azurerm#26739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

latest

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

Auth

### Terraform Configuration Files

Attempting to execute a pipeline from inside a container in AKS doesn't work following the documentation for authorising with an AKS workload identity found here `https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/aks_workload_identity`

note that my devops agent runs on kubernetes, i am not directly executing terraform on my cluster

Pipeline Code:

````
parameters:
  environment:
  tfVarFileLocation: 
  backendConfigLocation: 
  terraformDirectory: 
  subscriptionId:

jobs:
  - deployment: ${{ parameters.environment }}
    displayName:  ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: TerraformInstaller@1
              inputs:
                terraformVersion: 'latest'

            - bash: |
                echo '##vso[task.setvariable variable=ARM_USE_AKS_WORKLOAD_IDENTITY]true'
                echo '##vso[task.setvariable variable=ARM_USE_CLI]false'
                echo '##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]${{ parameters.subscriptionId }}'
              displayName: Set Variables
              

            - bash: |
                echo $ARM_USE_CLI
                echo $ARM_USE_AKS_WORKLOAD_IDENTITY
                echo $ARM_SUBSCRIPTION_ID
                
                terraform init -backend-config="${{ parameters.backendConfigLocation }}" 
              displayName: Init
              workingDirectory: ${{ parameters.terraformDirectory }}
                   
            
            - bash: |
                terraform plan -var-file=${{ parameters.tfVarFileLocation }}
      displayName: Plan
              workingDirectory: ${{ parameters.terraformDirectory }}
                
            - bash: |
                terraform apply -var-file=${{ parameters.backendConfigLocation }} -auto-approve
              displayName: Apply
              workingDirectory: ${{ parameters.terraformDirectory }}
````

### Debug Output/Panic Output

```shell
`Error building ARM Config: obtain subscription(XXXXXX) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.`
```

### Expected Behaviour

Terraform init to be successful

### Actual Behaviour

fails with error `Error building ARM Config: obtain subscription(XXXXXX) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.`
