### ISSUE TITLE
azurerm_kubernetes_cluster version

### ISSUE THREAD

**Issue by dannymyers** [terraform-providers/terraform-provider-azurerm#2947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_resource_group" "test" {
  name     = "acctestRG1"
  location = "East US"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestaks1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  dns_prefix          = "acctestagent1"

  agent_pool_profile {
    name            = "default"
    count           = 1
    vm_size         = "Standard_D1_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }

  tags {
    Environment = "Production"
  }
}
```

### Expected Behavior

According to the documentation, the latest recommended Kubernetes Version should be selected.

### Actual Behavior

Version 1.9.11 was selected (1.12.5 is available as of today in the dropdown via the portal). What makes a version recommended?

### Steps to Reproduce

1. `terraform apply`

**Comment by MattMencel** [comment]
What region?  I am not positive this is why, but if you `get-versions` in the region it does return one `default: true` version.

`az aks get-versions -l eastus -o json | jq '.orchestrators[] | select(.default == true)'`

``` yaml
{
  "default": true,
  "orchestratorType": "Kubernetes",
  "orchestratorVersion": "1.10.12",
  "upgrades": [
    {
      "orchestratorType": null,
      "orchestratorVersion": "1.11.6"
    },
    {
      "orchestratorType": null,
      "orchestratorVersion": "1.11.7"
    }
  ]
}
```
