### ISSUE TITLE
Regarding #1662: Allow Container ~Group~ Ports to be specifically specified rather than aggregating the container ports

### ISSUE THREAD

**Issue by Dikymon** [terraform-providers/terraform-provider-azurerm#4413]
This is basically a rehash of issue [#1662](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1662) which was closed as part of [#1930](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1930) but does not seem to fix the issue stated in #1662

A container groups exposed ports are still an aggregation of the defined containers ports, eventhough ARM allows for a subset of ports to be exposed or am I missing something?

See [resource_arm_container_group.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_container_group.go)

Thanks

**Comment by simondevolutions** [comment]
It is also the way I am understanding it. It would be very convenient since one of the points of deploying a container group is having internal communication inside your instance that doesn't need to be exposed.

**Comment by amasover** [comment]
[This how-to from Microsoft is a really good example of the use-case](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-container-group-ssl).

Simplifying their example yaml a little bit to illustrate:

```
name: app-with-ssl
properties:
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    type: Public
  containers:
  - name: nginx-with-ssl
    properties:
      image: nginx
      ports:
      - port: 443
        protocol: TCP
  - name: my-app
    properties:
      image: mcr.microsoft.com/azuredocs/aci-helloworld
      ports:
      - port: 80
        protocol: TCP
```

I think a potential Terraform config could look like this:

```
resource "azurerm_container_group" "app-with-ssl" {
  name = "app-with-ssl"
  ip_address {
    type = "public"
    ports {
      port = 443
      protocol = "TCP"
  }
  container {
    name = "nginx-with-ssl"
    image = "nginx"
    ports {
      port = 443
      protocol = "TCP"
    }
  }
  container {
    name = "my-app"
    image = "mcr.microsoft.com/azuredocs/aci-helloworld"
    ports {
      port = 80
      protocol = "TCP"
    }
  }
}
```

But note that currently we set `ip_address_type` and `dns_name_label` both at the top level. So if we keep things closer to how they are today, the top part of that would look like this:

```
resource "azurerm_container_group" "app-with-ssl" {
  name = "app-with-ssl"
  ip_address_type = "public"
  ports {
    port = 443
    protocol = "TCP"
  }
```

Semantically it seems to me that setting `dns_name_label`, `ports`, and `type` on the `ip_address` makes more sense than setting them all separately underneath the top-level resource. But I'm no expert on Terraform conventions. And updating it at this point would break backwards compatibility.

**Reference:**

[yaml reference](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-reference-yaml)
[api reference](https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/createorupdate#ipaddress)
