### ISSUE TITLE
Feature Request: Web App for Containers support

### ISSUE THREAD

**Issue by mojodna** [terraform-providers/terraform-provider-azurerm#580]
Terraform version:

```
Terraform v0.11.0
+ provider.azurerm v0.3.3
+ provider.random v1.0.0
```

I'd like to automate deployment of Docker containers as Web Apps to a Linux App Service Plan, i.e. using the equivalent of `az webapp create ... --deployment-container-image-name <image URL>`.

**Comment by tombuildsstuff** [comment]
Hey @mojodna 

Thanks for opening this issue :)

Taking a quick look into this issue - this appears to be a regular App Service with the `linuxFxVersion` field within the site configuration set to `DOCKER|(container name)+(:optional version)` (e.g. `DOCKER|golang` or `DOCKER|golang:latest`); and an app setting of `WEBSITES_ENABLE_APP_SERVICE_STORAGE` = `false`.

We don't support this field right now [due to a bug in the Azure App Service API](https://github.com/Azure/azure-rest-api-specs/issues/1698) - that said once the bug in the API is fixed we can take a look into supporting this functionality. Until then, you should be able to achieve the same thing with [the `azurerm_template_deployment` resource](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html).

Thanks!

**Comment by mojodna** [comment]
thanks @tombuildsstuff!

**Comment by mojodna** [comment]
I picked this back up today and haven't been having any luck getting it to work (and can't find any relevant docs). Here's my template:

```yaml
resource "azurerm_template_deployment" "test" {
  name = "template-01"
  resource_group_name = "${azurerm_resource_group.rg.name}"

  template_body = <<DEPLOY
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "app_service_plan_id": {
      "type": "string",
      "metadata": {
        "description": "App Service Plan ID"
      }
    },
    "name": {
      "type": "string",
      "metadata": {
        "description": "App Name"
      }
    },
    "image": {
      "type": "string",
      "metadata": {
        "description": "Docker image"
      }
    }
  },
  "variables": {
  },
  "resources": [
    {
      "type": "Microsoft.Web/sites",
      "kind": "app,linux,container",
      "name": "[parameters('name')]",
      "properties": {
        "siteConfig": {
          "appSettings": [
            {
              "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
              "value": "false"
            }
          ],
          "linuxFxVersion": "[concat('DOCKER|', parameters('image'))]"
        },
        "name": "[parameters('name')]",
        "serverFarmId": "[parameters('app_service_plan_id')]"
      },
      "apiVersion": "2016-08-01",
      "location": "[resourceGroup().location]"
    }
  ]
}
DEPLOY

  parameters {
    name = "golang"
    image = "golang"
    app_service_plan_id = "${azurerm_app_service_plan.plan.id}"
 }

  deployment_mode = "Incremental"
}
```

Things generally look like they're created properly, but Azure isn't picking it up as a Docker app for some reason.

Help?
