### ISSUE TITLE
use azurerm_cognitive_account create Bing.Search.v7 with error endpoint url

### ISSUE THREAD

**Issue by myliyifei** [terraform-providers/terraform-provider-azurerm#8136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

_terraform {
  required_version = "= 0.13.0"
}
provider "azurerm" {
  version       = "= 2.23.0"
  features {}
}_

### Affected Resource(s)

* `azurerm_cognitive_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_account" "accounts" {
  for_each              = var.parameters
  
  name                  = each.key
  resource_group_name   = var.resource_group_name
  location              = each.value.location
  kind                  = each.value.kind
  sku_name              = each.value.sku_name
  tags                  = var.tags
}
```

### Expected Behavior

I created a bing search V7 service using the Azure portal and used AZ CLI to display the relevant properties.

In contrast to the bing search service generated using terraform, the following two properties are different (it's only correct to keep the same name as the service)：

> customSubDomainName: stock-news
> endpoint: https://stock-news.cognitiveservices.azure.com/

_az cognitiveservices account show --name stock-news -g stock -o yamlc_

```
identity: null
kind: Bing.Search.v7
location: global
name: stock-news
properties:
  apiProperties:
    eventHubConnectionString: null
    qnaRuntimeEndpoint: null
    statisticsEnabled: null
    storageAccountConnectionString: null
  callRateLimit:
    rules:
    - count: 3
      key: default
      matchPatterns:
      - method: '*'
        path: '*'
      renewalPeriod: 1
  capabilities: []
  customSubDomainName: stock-news
  dateCreated: '2020-08-15T04:42:16.1041231Z'
  encryption: null
  endpoint: https://stock-news.cognitiveservices.azure.com/
  internalId: 349c8758d5b34b1ab8f2efd01da1155a
  networkAcls: null
  privateEndpointConnections: null
  provisioningState: Succeeded
  publicNetworkAccess: Enabled
  quotaLimit:
    rules:
    - count: 1000
      key: default
      matchPatterns:
      - method: '*'
        path: '*'
      renewalPeriod: 2592000
  userOwnedStorage: null
resourceGroup: stock
sku:
  name: F1
  tier: null
tags: null
type: Microsoft.CognitiveServices/accounts
```

### Actual Behavior

Using terraform to generate the search v7 service and then using the AZ CLI to display the relevant properties, the two items were found to be null or not the same as the service name.

>   customSubDomainName: null
>   endpoint: https://api.cognitive.microsoft.com/

```
identity: null
kind: Bing.Search.v7
location: global
name: stock-news
properties:
  apiProperties:
    eventHubConnectionString: null
    qnaRuntimeEndpoint: null
    statisticsEnabled: null
    storageAccountConnectionString: null
  callRateLimit:
    rules:
    - count: 3
      key: default
      matchPatterns:
      - method: '*'
        path: '*'
      renewalPeriod: 1
  capabilities: []
  customSubDomainName: null
  dateCreated: '2020-08-15T04:35:39.6686651Z'
  encryption: null
  endpoint: https://api.cognitive.microsoft.com/
  internalId: 815e2bf3e9df4f41b72c2ec17f4e93f5
  networkAcls: null
  privateEndpointConnections: null
  provisioningState: Succeeded
  publicNetworkAccess: Enabled
  quotaLimit:
    rules:
    - count: 1000
      key: default
      matchPatterns:
      - method: '*'
        path: '*'
      renewalPeriod: 2592000
  userOwnedStorage: null
resourceGroup: stock
sku:
  name: F1
  tier: Free
tags:
  environment: sandbox
  managed_by: TERRAFORM
  project: stock
type: Microsoft.CognitiveServices/accounts
```

Terraform Outputs:

cognitive_endpoint = [
  "https://**api**.cognitive.microsoft.com/",
]

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
